name: mumble_sounds_example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mumble_sounds:
    path: ..
    
flutter:
  uses-material-design: true